app:
    resource: '@AppBundle/Controller/'
    type: annotation
_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_user_profile_edit:
    path: /profile/edit
    controller: AppBundle\Controller\ProfileController::editAction